name: Deploy new production model
on:
  push:

jobs:
  helloworld:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install and Configure Outerbounds
        run: |-
          pip install -U outerbounds && \
          outerbounds service-principal-configure \
          --name <YOUR-SERVICE-PRINCIPAL-NAME> \
          --deployment-domain <YOUR-OUTERBOUNDS-DEPLOYMENT-NAME> \
          --perimeter <YOUR-OUTERBOUNDS-PERIMETER-NAME> \
          --github-actions

      - name: Run helloworld flow
        run: |-
          python evaluate_new_model_flow.py run --with card